### ISSUE TITLE
`geo_index': undefined method `define_singleton_method'

### ISSUE THREAD

**Issue by salbito** [kristianmandrup/mongoid-geo#32]
With the recent changes to how indexes are defined and are created some problems have crept up. Here is the stack error.

``` ruby
/home/salbito/.rvm/gems/ree-1.8.7-2010.02/bundler/gems/mongoid-geo-24f205367686/lib/mongoid/geo/index.rb:9:in `geo_index': undefined method `define_singleton_method' for Ping:Class (NoMethodError)
        from /home/salbito/Source/PingPang/app/models/ping.rb:9
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:227:in `load_dependency'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:346:in `require_or_load'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:300:in `depend_on'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:216:in `require_dependency'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/bundler/gems/mongoid-8f827db43826/lib/rails/mongoid.rb:55:in `load_model'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/bundler/gems/mongoid-8f827db43826/lib/rails/mongoid.rb:18:in `load_models'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/bundler/gems/mongoid-8f827db43826/lib/rails/mongoid.rb:17:in `each'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/bundler/gems/mongoid-8f827db43826/lib/rails/mongoid.rb:17:in `load_models'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/paths.rb:102:in `each'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/paths.rb:102:in `each'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/bundler/gems/mongoid-8f827db43826/lib/rails/mongoid.rb:16:in `load_models'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/bundler/gems/mongoid-8f827db43826/lib/mongoid/railtie.rb:86:in `_callback_before_5'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-3.0.7/lib/active_support/callbacks.rb:425:in `_run_prepare_callbacks'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.7/lib/action_dispatch/middleware/callbacks.rb:40:in `initialize'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:33:in `new'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:33:in `build'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:79:in `build'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/application.rb:209:in `inject'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:79:in `each'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:79:in `inject'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.7/lib/action_dispatch/middleware/stack.rb:79:in `build'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/application.rb:162:in `build_middleware_stack'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/application/finisher.rb:35
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `instance_exec'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `run'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/initializable.rb:50:in `run_initializers'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `each'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `run_initializers'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/application.rb:134:in `initialize!'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/application.rb:77:in `send'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/railties-3.0.7/lib/rails/application.rb:77:in `method_missing'
        from /home/salbito/Source/PingPang/config/environment.rb:5
        from /home/salbito/Source/PingPang/spec/spec_helper.rb:3:in `require'
        from /home/salbito/Source/PingPang/spec/spec_helper.rb:3
        from /home/salbito/Source/PingPang/spec/models/choice_spec.rb:1:in `require'
        from /home/salbito/Source/PingPang/spec/models/choice_spec.rb:1
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/rspec-core-2.6.2/lib/rspec/core/configuration.rb:419:in `load'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/rspec-core-2.6.2/lib/rspec/core/configuration.rb:419:in `load_spec_files'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/rspec-core-2.6.2/lib/rspec/core/configuration.rb:419:in `map'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/rspec-core-2.6.2/lib/rspec/core/configuration.rb:419:in `load_spec_files'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/rspec-core-2.6.2/lib/rspec/core/command_line.rb:18:in `run'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/rspec-core-2.6.2/lib/rspec/core/runner.rb:80:in `run_in_process'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/rspec-core-2.6.2/lib/rspec/core/runner.rb:69:in `run'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/gems/rspec-core-2.6.2/lib/rspec/core/runner.rb:11:in `autorun'
        from /home/salbito/.rvm/gems/ree-1.8.7-2010.02/bin/rspec:19
```

**Comment by ryanong** [comment]
I'll check it out in a minute

**Comment by kristianmandrup** [comment]
Yeah, the #define_singleton_method is a ruby 1.9 specific method. Couldn't figure out how to do it with Ruby 1.8.7.
A simple hack could be a simple respond_to? check to break out, until we find a ruby 1.8 compatible solution. But I'm sure ryanong can quickly sort it out ;)

**Comment by salbito** [comment]
Hey so I pushed up my refactoring of the mongoid_geo gem. Alot of changes in there. Still needs some work and cleanup. Specs are still a bit broken but I'm trying to structure the project first for easy maintainability and testing.

**Comment by salbito** [comment]
Really github a comment and close button?

**Comment by ryanong** [comment]
Fixed forced index creation
